### PR TITLE
Upgrade to Quarkus 2.0.0.CR3

### PR DESCRIPTION
**Pull request by ppalaga**

### CODE REVIEW

**Comment by ppalaga** [comment]
@jtama could you please review?

**Comment by jtama** [comment]
I'm on hollydays, I will check next week, though I want to migrate minio ans after upgrade to Quarkus 2.x.
Thanks for the work ;) !

**Comment by ppalaga** [comment]
Thanks @jtama, this is not urgent. Enjoy the rest of your holiday!

**Comment by jtama** [comment]
@ppalaga The minio part of this PR has been processed in #52.  Will be releasing a 0.2.2, and a 1.0 once migration to quarkus 2.X is done.

**Comment by jtama** [comment]
Leaving PR open for now, will close it when all is done.

**Comment by ppalaga** [comment]
Thanks, @jtama!

**Comment by ppalaga** [comment]
Rebased an upgraded to Quarkus 2.0.0.CR2

**Comment by ppalaga** [comment]
Upgraded to Quarkus 2.0.0.CR3

**Comment by ppalaga** [comment]
We'd very much appreciate a quarkus-minio release based on Quarkus 2.0.0.CR3 to be able to test with Camel Quarkus and even on Quarkus Platform. Is there any hope for it?

**Comment by jtama** [comment]
> We'd very much appreciate a quarkus-minio release based on Quarkus 2.0.0.CR3 to be able to test with Camel Quarkus and even on Quarkus Platform. Is there any hope for it?

Yes, but I may create a branch for 2.X release.

**Comment by jtama** [comment]
Can you change branch destination to branch 2.X ?

**Comment by ppalaga** [comment]
Done, thanks!

**Pull request merged**
