### PR TITLE
Bump minio

### PR DESCRIPTION
**Pull request by SpeedsterF2**
Stop waiting for upstream to drop okhttp from bom.

Preconditions for using okhttp 4.x are fullfilled!

### CODE REVIEW

**Comment by jtama** [comment]
I guess you issue comes from somewhere here (https://github.com/minio/minio-java/blob/8.4.6/api/src/main/java/io/minio/UploadSnowballObjectsArgs.java#L28)

**Comment by SpeedsterF2** [comment]
> I guess you issue comes from somewhere here (https://github.com/minio/minio-java/blob/8.4.6/api/src/main/java/io/minio/UploadSnowballObjectsArgs.java#L28)

I need to get my hotfix on prod, then I can try to tackle the Random usage problem.
Do you want me to keep the okio related lines in the pom.xml? I think I can drop them.
Maybe add the info to the README.md. Something along the line:
If your Quarkus application actually used okio, then we suggest to overwrite the version definition from the quarkus bom to a version compatible with the okhttp used by this extension, e.g. okio v2.3.0.

**Comment by SpeedsterF2** [comment]
@jtama 
BTW, would you be interested in a k8s readiness probe similar to that in the rabbitmq extension:
https://github.com/quarkiverse/quarkus-rabbitmq-client/blob/master/runtime/src/main/java/io/quarkiverse/rabbitmqclient/RabbitMQReadyCheck.java
It uses a java.net.Socket to "ping" the server.

There is another PR open, which uses try-with-resources to close the Socket after usage.

**Comment by jtama** [comment]
Why not but thé probe should only be there if microprofile is added by applications using the extension.

**Comment by SpeedsterF2** [comment]
> I guess you issue comes from somewhere here (https://github.com/minio/minio-java/blob/8.4.6/api/src/main/java/io/minio/UploadSnowballObjectsArgs.java#L28)

Looks like we need a RuntimeInitializedClassBuildItem:
https://quarkus.io/guides/writing-native-applications-tips#delay-class-initialization

**Comment by jtama** [comment]
@SpeedsterF2  One last question : Have you checked the size of the resulting lib ?

**Comment by jtama** [comment]
@SpeedsterF2 Could you please rebase and squash your commits ?

**Comment by jtama** [comment]
@SpeedsterF2 Did you had a chance to squash everything ?

**Comment by SpeedsterF2** [comment]
Sorry for not reacting in time, had lots to do at work.

**Pull request merged**
